spring:
  datasource:
      url: jdbc:mysql://localhost:3306/securitytest?characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


 # 原因： 这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
 # 解决：在application.properties里配置：spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER。
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  type-aliases-package: classpath:com/ysh/Pojo/*
logging:
  level:
    com/ysh/Mapper/userMapper: debug
